// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Agent 是一个角色文件的完整内存表示。
 * 字符串字段用指针区分"未设置"与"显式设为空"；布尔用指针同理。
 */
export interface Agent {
    "name": string;
    "description": string;
    "color": string | null;
    "model": string | null;
    "thoughtLevel": string | null;
    "tools": string[] | null;
    "disallowedTools": string[] | null;
    "skills": string[] | null;
    "permissionMode": string | null;
    "maxTurns": number | null;
    "background": boolean | null;
    "injectAgentsMd": boolean | null;
    "mcpServers": string[] | null;
    "body": string;
    "unknownLists"?: { [_ in string]?: string[] | null } | null;
    "unknownLines"?: string[] | null;

    /**
     * 非 frontmatter 元数据
     */
    "fileName": string;
    "filePath": string;
    "raw"?: string;
}

/**
 * Summary 是列表用摘要。
 */
export interface Summary {
    "fileName": string;
    "name": string;
    "description": string;
    "permissionMode": string;
    "model": string;
    "toolCount": number;
    "skillCount": number;
    "maxTurns": number;
    "bodyLines": number;
    "modifiedAt": string;
}
