// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * API 是暴露给前端的唯一服务：ZCode 自定义子智能体（~/.zcode/agents/*.md）的
 * 查看、编辑、新建、删除与权限模式切换。所有写操作都会先自动备份。
 * mainWin/floatWin 由 main 直接注入（不走绑定，避免接口参数被生成成 TS）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentfile$0 from "./internal/agentfile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sessionmode$0 from "./internal/sessionmode/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as zconfig$0 from "./internal/zconfig/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AgentsDir 返回当前角色目录。
 */
export function AgentsDir(): $CancellablePromise<string> {
    return $Call.ByID(539930373);
}

/**
 * CreateAgent 新建角色。
 */
export function CreateAgent(ag: agentfile$0.Agent): $CancellablePromise<agentfile$0.Summary> {
    return $Call.ByID(1855042757, ag);
}

/**
 * DeleteAgent 备份后删除角色。
 */
export function DeleteAgent(fileName: string): $CancellablePromise<void> {
    return $Call.ByID(2445794112, fileName);
}

/**
 * FloatPanelVisible 返回悬浮面板当前是否可见。
 */
export function FloatPanelVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(2777181554);
}

/**
 * GetAgent 读取单个角色的完整定义。
 */
export function GetAgent(fileName: string): $CancellablePromise<agentfile$0.Agent | null> {
    return $Call.ByID(4180049293, fileName);
}

/**
 * HideFloatPanel 收起悬浮面板（不等同于退出）。
 */
export function HideFloatPanel(): $CancellablePromise<void> {
    return $Call.ByID(2311097008);
}

/**
 * ListAgents 返回全部角色摘要（按文件名排序）。
 */
export function ListAgents(): $CancellablePromise<agentfile$0.Summary[] | null> {
    return $Call.ByID(573435398);
}

/**
 * ListSessionModes 列出 ZCode 全部有执行状态记录的会话及其持久化模式。
 */
export function ListSessionModes(): $CancellablePromise<sessionmode$0.SessionModeInfo[] | null> {
    return $Call.ByID(241681060);
}

/**
 * Meta 返回表单下拉选项（模型、模式、工具、技能、内置智能体）。
 */
export function Meta(): $CancellablePromise<zconfig$0.Meta | null> {
    return $Call.ByID(3595710269);
}

/**
 * SaveAgent 保存角色。改名时走"新建 + 备份删除旧文件"路径。
 */
export function SaveAgent(req: $models.SaveRequest): $CancellablePromise<agentfile$0.Summary> {
    return $Call.ByID(3058914502, req);
}

/**
 * SetAllPermissionModes 批量切换全部角色，返回成功的数量。
 */
export function SetAllPermissionModes(mode: string): $CancellablePromise<number> {
    return $Call.ByID(912143492, mode);
}

/**
 * SetPermissionMode 切换单个角色的权限模式（保存前自动备份）。
 */
export function SetPermissionMode(fileName: string, mode: string): $CancellablePromise<agentfile$0.Summary> {
    return $Call.ByID(2856165496, fileName, mode);
}

/**
 * SetSessionMode 覆盖目标会话的持久化模式（下次该会话恢复/重启 ZCode 后生效）。
 */
export function SetSessionMode(sessionID: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(1480478743, sessionID, mode);
}

/**
 * ShowMainWindow 从悬浮面板切换到主窗口（切换语义：收起悬浮面板再显示主窗口）。
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(1498906584);
}

/**
 * ThoughtLevels 按模型引用返回推理档位候选；无匹配时返回通用候选。
 */
export function ThoughtLevels(ref: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1712749042, ref);
}

/**
 * ToggleFloatPanel 切换悬浮面板可见性，返回切换后的可见性。
 */
export function ToggleFloatPanel(): $CancellablePromise<boolean> {
    return $Call.ByID(3304502772);
}

/**
 * Validate 对表单内容做静态校验。error 级问题阻止保存，warn 级仅提示。
 */
export function Validate(ag: agentfile$0.Agent): $CancellablePromise<$models.Issue[] | null> {
    return $Call.ByID(135085342, ag);
}
