// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentfile$0 from "./internal/agentfile/models.js";

/**
 * Issue 是一条校验结果；level 为 "error"（阻止保存）或 "warn"（提示不阻止）。
 */
export interface Issue {
    "level": string;
    "message": string;
}

/**
 * SaveRequest 是保存请求；OriginalFileName 用于处理改名（另存为新文件并删旧文件）。
 */
export interface SaveRequest {
    "agent": agentfile$0.Agent;
    "originalFileName": string;
}
