// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuiltInAgent 是内置智能体（无文件，只读展示）。
 */
export interface BuiltInAgent {
    "name": string;
    "model"?: string;
    "desc": string;
}

/**
 * Meta 是前端表单需要的全部静态选项。
 */
export interface Meta {
    "modes": ModeOption[] | null;
    "colors": string[] | null;
    "thoughtLevels": string[] | null;
    "toolGroups": ToolGroup[] | null;
    "skills": string[] | null;
    "models": ModelOption[] | null;
    "builtIns": BuiltInAgent[] | null;
    "agentsDir": string;
    "zcodeHome": string;
    "configFound": boolean;
}

/**
 * ModeOption 是权限模式下拉项。
 */
export interface ModeOption {
    "value": string;
    "label": string;
    "desc": string;

    /**
     * Internal 标注该取值在客户端内部被归一到哪一档。
     */
    "internal": string;
}

/**
 * ModelOption 是一个可选的模型引用（provider/model）。
 */
export interface ModelOption {
    "ref": string;
    "providerName": string;
    "model": string;
}

/**
 * ToolGroup 是工具复选框分组。
 */
export interface ToolGroup {
    "name": string;
    "tools": string[] | null;
}
