// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionModeInfo 是一个会话的持久化模式状态。
 */
export interface SessionModeInfo {
    "sessionId": string;
    "title": string;
    "isSubagent": boolean;
    "parentId": string;
    "mode": string;
    "planEnabled": boolean;
    "updatedAt": string;
    "hasState": boolean;
}
